### ISSUE TITLE
Only question about logstash

### ISSUE THREAD

**Issue by kwLaur** [saudurehman/logstash_jms_ibm_mq#2]
Hello,

I did all the steps in your tutorial but when I want to start the logstash I have the following error:

fagetl@E0907421:/mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1$ bin/logstash -f jms.conf
Using bundled JDK: /mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
/mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
Sending Logstash logs to /mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/logs which is now configured via log4j2.properties
[2021-09-20T17:28:04,449][INFO ][logstash.runner          ] Log4j configuration path used is: /mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/config/log4j2.properties
[2021-09-20T17:28:04,465][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.14.1", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.11+9 on 11.0.11+9 +indy +jit [linux-x86_64]"}
[2021-09-20T17:28:06,315][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2021-09-20T17:28:15,543][INFO ][org.reflections.Reflections] Reflections took 241 ms to scan 1 urls, producing 120 keys and 417 values
[2021-09-20T17:28:16,821][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2021-09-20T17:28:18,453][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/jms.conf"], :thread=>"#<Thread:0x3436b139 run>"}
[2021-09-20T17:28:20,038][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>1.58}
[2021-09-20T17:28:21,335][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2021-09-20T17:28:21,484][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}

[2021-09-20T17:28:30,137][WARN ][logstash.inputs.jms      ][main][cd9d7406cf1a4849de1b001f502ef1188f203796c6b40a7743b812860a39aa5b] JMS Consumer Died {:exception=>"NameError", :exception_message=>"cannot load Java class javax.jms.DeliveryMode", :backtrace=>["org/jruby/javasupport/JavaClass.java:292:in `for_name'", "org/jruby/javasupport/JavaClass.java:288:in `for_name'", "org/jruby/javasupport/JavaUtilities.java:39:in `get_proxy_class'", "uri:classloader:/jruby/java/core_ext/object.rb:44:in `block in java_import'", "org/jruby/RubyArray.java:2588:in `map'", "uri:classloader:/jruby/java/core_ext/object.rb:37:in `java_import'", "/mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/vendor/bundle/jruby/2.5.0/gems/jruby-jms-1.3.0-java/lib/jms/imports.rb:3:in `<module:JMS>'", "/mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/vendor/bundle/jruby/2.5.0/gems/jruby-jms-1.3.0-java/lib/jms/imports.rb:2:in `<main>'", "org/jruby/RubyKernel.java:974:in `require'", "/mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/vendor/bundle/jruby/2.5.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/vendor/bundle/jruby/2.5.0/gems/jruby-jms-1.3.0-java/lib/jms/connection.rb:100:in `fetch_dependencies'", "/mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/vendor/bundle/jruby/2.5.0/gems/jruby-jms-1.3.0-java/lib/jms/connection.rb:158:in `initialize'", "/mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/vendor/bundle/jruby/2.5.0/gems/logstash-input-jms-3.1.2-java/lib/logstash/inputs/jms.rb:225:in `run'", "/mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/logstash-core/lib/logstash/java_pipeline.rb:405:in `inputworker'", "/mnt/c/Users/laurentiu.faget2/Downloads/logstash-7.14.1/logstash-core/lib/logstash/java_pipeline.rb:396:in `block in start_input'"]}

Did you encounter this problem?
Thanks

**Comment by kwLaur** [comment]
Sorry, my mistake, in the mq.yml file I was using the windows path to require_jars. Thanks
